[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
presale = "BTNaNtGC5sTfNUbusLBRuMViPT2wNBvkzCem5HEDBUMM"

[programs.mainnet]
presale = "D1z7DrkYk3Xvnyz9BdToK5zPnHSKHXL3RTUQktHusiif"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "https://mainnet.helius-rpc.com/?api-key=888deea7-ded4-44d9-8906-e1776e2a8f4e"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
